# Generated by Django 5.0.3 on 2024-03-28 10:37

import django.db.models.deletion
import gnosis_app.models
import markdownfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=gnosis_app.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam')], default='en', max_length=10)),
                ('department', models.CharField(choices=[('gen', 'General'), ('cse', 'Computer Science and Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ece', 'Electronics and Communication Engineering'), ('che', 'Chemical Engineering'), ('bt', 'Biotechnology'), ('it', 'Information Technology'), ('ae', 'Aeronautical Engineering'), ('ae', 'Automobile Engineering'), ('ie', 'Industrial Engineering'), ('mse', 'Materials Science and Engineering'), ('ne', 'Nuclear Engineering'), ('pe', 'Petroleum Engineering'), ('mn', 'Mining Engineering'), ('oe', 'Ocean Engineering'), ('bce', 'Biochemical Engineering'), ('ie', 'Instrumentation Engineering'), ('se', 'Systems Engineering')], default='gen', max_length=100)),
                ('restrict_comments', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('favourite_ques', models.ManyToManyField(blank=True, related_name='favourite_ques', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownfield.models.MarkdownField(rendered_field='content_rendered')),
                ('content_rendered', markdownfield.models.RenderedMarkdownField(default='')),
                ('video', models.FileField(blank=True, null=True, upload_to=gnosis_app.models.user_directory_path)),
                ('audio', models.FileField(blank=True, null=True, upload_to=gnosis_app.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_comment', to='gnosis_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='gnosis_app.comment')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_reply', to='gnosis_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
