# Generated by Django 5.0.3 on 2024-04-07 01:54

import gnosis_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=gnosis_app.models.user_directory_path),
        ),
    ]
