# Generated by Django 5.0.2 on 2024-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('gen', 'General'), ('cse', 'Computer Science and Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ece', 'Electronics and Communication Engineering'), ('che', 'Chemical Engineering'), ('bt', 'Biotechnology'), ('it', 'Information Technology'), ('ae', 'Aeronautical Engineering'), ('ae', 'Automobile Engineering'), ('ie', 'Industrial Engineering'), ('mse', 'Materials Science and Engineering'), ('ne', 'Nuclear Engineering'), ('pe', 'Petroleum Engineering'), ('mn', 'Mining Engineering'), ('oe', 'Ocean Engineering'), ('bce', 'Biochemical Engineering'), ('ie', 'Instrumentation Engineering'), ('se', 'Systems Engineering')], default='gen', max_length=100),
        ),
    ]
