# Generated by Django 5.0.2 on 2024-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0002_question_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam')], default='en', max_length=10),
        ),
    ]
