# Generated by Django 5.0.2 on 2024-03-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0003_alter_question_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='language',
        ),
    ]
