# Generated by Django 5.0.3 on 2024-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0003_question_preferred_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='preferred_ans',
            field=models.CharField(choices=[('any', 'Any Type'), ('text', 'Text'), ('image', 'Image'), ('video', 'Audio'), ('audio', 'Video')], default='any', max_length=100),
        ),
    ]
