# Generated by Django 5.0.2 on 2024-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0004_rename_status_question_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
