# Generated by Django 5.0.2 on 2024-03-26 04:49

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnosis_app', '0005_alter_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownfield.models.MarkdownField(rendered_field='content_rendered'),
        ),
    ]
